import Layout from "@/layout/Layout";
import NextAuthProvider from "@/provider/NextAuthProvider";
import { yekanBakh } from "@/utils/fonts";
import "./globals.css";

export const metadata = {
  title: "پروژه املاک - ماوایی",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekanBakh.className}>
        <NextAuthProvider>
          <Layout>{children}</Layout>
        </NextAuthProvider>
      </body>
    </html>
  );
}
